import Provider from "./provider";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Televora-AI",
  icons: {
    icon: "/favicon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="transition-colors duration-300">
      <body
        className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:text-white min-h-screen transition-colors duration-300`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}




